name: Run URL Collect and Extract

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{secrets.KLTN_DEMO_TOKEN}}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run URLs collecting
      run: python urls_collecting.py  

    - name: Run URLs filtering
      run: python URLs_Filter.py
    
    - name: Run feature extraction
      run: python feature_extraction.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Thêm tất cả thay đổi vào staging
        git add .
        
        # Kiểm tra có thay đổi nào không
        if ! git diff --cached --quiet; then
          git commit -m "Update generated files on $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
        else
          echo "No changes to commit."
        fi
